import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import * as fs from "fs";
import { generateEntrypoint } from "../../../src/cli/sync/entrypoint";
import { Worker } from "../../../src/bindings/worker";
import { DurableObject } from "../../../src/bindings/durable-object";

// Mock fs.writeFileSync
vi.mock("fs", async () => {
	const actual = await vi.importActual("fs");
	return {
		...actual,
		writeFileSync: vi.fn(),
	};
});

describe("generateEntrypoint", () => {
	beforeEach(() => {
		vi.clearAllMocks();
	});

	describe("basic entrypoint generation", () => {
		it("generates entrypoint with re-exports from user entry", () => {
			const worker = Worker({
				name: "my-worker",
				entryPoint: "./src/my-worker/index.ts",
			});

			generateEntrypoint(worker);

			expect(fs.writeFileSync).toHaveBeenCalledWith(
				".better-wrangler/my-worker.entry.ts",
				expect.stringContaining("export * from '../src/my-worker/index';")
			);
		});

		it("includes default export re-export", () => {
			const worker = Worker({
				name: "my-worker",
				entryPoint: "./src/my-worker/index.ts",
			});

			generateEntrypoint(worker);

			expect(fs.writeFileSync).toHaveBeenCalledWith(
				".better-wrangler/my-worker.entry.ts",
				expect.stringContaining("export { default } from '../src/my-worker/index';")
			);
		});

		it("includes auto-generated comment", () => {
			const worker = Worker({
				name: "my-worker",
				entryPoint: "./src/my-worker/index.ts",
			});

			generateEntrypoint(worker);

			expect(fs.writeFileSync).toHaveBeenCalledWith(
				".better-wrangler/my-worker.entry.ts",
				expect.stringContaining("// Auto-generated by better-wrangler - DO NOT EDIT")
			);
		});

		it("returns the entrypoint path", () => {
			const worker = Worker({
				name: "my-worker",
				entryPoint: "./src/my-worker/index.ts",
			});

			const result = generateEntrypoint(worker);

			expect(result).toBe(".better-wrangler/my-worker.entry.ts");
		});
	});

	describe("DurableObject exports", () => {
		it("exports owned DurableObject classes", () => {
			const worker = Worker({
				name: "my-worker",
				entryPoint: "./src/my-worker/index.ts",
				bindings: {
					MY_DO: DurableObject({
						name: "MY_DO",
						className: "MyDurableObject",
						classPath: "./src/shared/my-do.ts",
					}),
				},
			});

			generateEntrypoint(worker);

			expect(fs.writeFileSync).toHaveBeenCalledWith(
				".better-wrangler/my-worker.entry.ts",
				expect.stringContaining("export { MyDurableObject } from '../src/shared/my-do';")
			);
		});

		it("does not export external DurableObject classes", () => {
			const externalDO = DurableObject({
				name: "EXTERNAL_DO",
				className: "ExternalDO",
				classPath: "./src/shared/external-do.ts",
			});
			externalDO._owner = "other-worker";

			const worker = Worker({
				name: "my-worker",
				entryPoint: "./src/my-worker/index.ts",
				bindings: {
					EXTERNAL_DO: externalDO,
				},
			});

			generateEntrypoint(worker);

			const writtenContent = (fs.writeFileSync as ReturnType<typeof vi.fn>).mock.calls[0][1];
			expect(writtenContent).not.toContain("ExternalDO");
		});

		it("exports multiple owned DurableObject classes", () => {
			const worker = Worker({
				name: "my-worker",
				entryPoint: "./src/my-worker/index.ts",
				bindings: {
					COUNTER: DurableObject({
						name: "COUNTER",
						className: "CounterDO",
						classPath: "./src/dos/counter.ts",
					}),
					SESSION: DurableObject({
						name: "SESSION",
						className: "SessionDO",
						classPath: "./src/dos/session.ts",
					}),
				},
			});

			generateEntrypoint(worker);

			const writtenContent = (fs.writeFileSync as ReturnType<typeof vi.fn>).mock.calls[0][1];
			expect(writtenContent).toContain("export { CounterDO } from '../src/dos/counter';");
			expect(writtenContent).toContain("export { SessionDO } from '../src/dos/session';");
		});
	});

	describe("validateWorkerName", () => {
		it("throws for worker names with invalid characters", () => {
			const worker = Worker({
				name: "my worker",
				entryPoint: "./src/my-worker/index.ts",
			});

			expect(() => generateEntrypoint(worker)).toThrow(
				'Invalid worker name "my worker"'
			);
		});

		it("throws for worker names with slashes", () => {
			const worker = Worker({
				name: "my/worker",
				entryPoint: "./src/my-worker/index.ts",
			});

			expect(() => generateEntrypoint(worker)).toThrow(
				'Invalid worker name "my/worker"'
			);
		});

		it("allows hyphens, underscores, and dots in worker names", () => {
			const worker = Worker({
				name: "my-worker_v1.0",
				entryPoint: "./src/my-worker/index.ts",
			});

			expect(() => generateEntrypoint(worker)).not.toThrow();
		});
	});

	describe("validatePath", () => {
		it("throws for entryPoint with path traversal", () => {
			const worker = Worker({
				name: "my-worker",
				entryPoint: "../../../etc/passwd",
			});

			expect(() => generateEntrypoint(worker)).toThrow(
				"entryPoint must be within project directory"
			);
		});

		it("throws for entryPoint with quotes", () => {
			const worker = Worker({
				name: "my-worker",
				entryPoint: "./src/my-worker/index'.ts",
			});

			expect(() => generateEntrypoint(worker)).toThrow(
				"entryPoint contains invalid characters"
			);
		});

		it("throws for classPath with path traversal", () => {
			const worker = Worker({
				name: "my-worker",
				entryPoint: "./src/my-worker/index.ts",
				bindings: {
					MY_DO: DurableObject({
						name: "MY_DO",
						className: "MyDurableObject",
						classPath: "../../../evil/do.ts",
					}),
				},
			});

			expect(() => generateEntrypoint(worker)).toThrow(
				"classPath must be within project directory"
			);
		});
	});

	describe("validateClassName", () => {
		it("throws for invalid class names", () => {
			const worker = Worker({
				name: "my-worker",
				entryPoint: "./src/my-worker/index.ts",
				bindings: {
					MY_DO: DurableObject({
						name: "MY_DO",
						className: "123InvalidClass",
						classPath: "./src/shared/do.ts",
					}),
				},
			});

			expect(() => generateEntrypoint(worker)).toThrow(
				'Invalid class name "123InvalidClass"'
			);
		});

		it("throws for class names with hyphens", () => {
			const worker = Worker({
				name: "my-worker",
				entryPoint: "./src/my-worker/index.ts",
				bindings: {
					MY_DO: DurableObject({
						name: "MY_DO",
						className: "My-Durable-Object",
						classPath: "./src/shared/do.ts",
					}),
				},
			});

			expect(() => generateEntrypoint(worker)).toThrow(
				'Invalid class name "My-Durable-Object"'
			);
		});

		it("allows valid JavaScript identifiers", () => {
			const worker = Worker({
				name: "my-worker",
				entryPoint: "./src/my-worker/index.ts",
				bindings: {
					MY_DO: DurableObject({
						name: "MY_DO",
						className: "_MyDurableObject$123",
						classPath: "./src/shared/do.ts",
					}),
				},
			});

			expect(() => generateEntrypoint(worker)).not.toThrow();
		});
	});

	describe("path normalization", () => {
		it("strips .ts extension from paths", () => {
			const worker = Worker({
				name: "my-worker",
				entryPoint: "./src/my-worker/index.ts",
			});

			generateEntrypoint(worker);

			const writtenContent = (fs.writeFileSync as ReturnType<typeof vi.fn>).mock.calls[0][1];
			expect(writtenContent).toContain("../src/my-worker/index");
			expect(writtenContent).not.toContain(".ts");
		});
	});
});
