import { writeFileSync } from "fs";
import { relative } from "path";
import type { WorkerConfig, Bindings } from "../types";
import type { DurableObjectBinding } from "../../bindings/durable-object";
import { generateWranglerConfig } from "../../generate";

const OUTPUT_DIR = ".better-wrangler";

/**
 * Generates a wrapper entrypoint file that re-exports the user's worker
 * and any Durable Object classes owned by this worker.
 * This allows wrangler to find DO classes without modifying user code.
 */
export function generateEntrypoint(worker: WorkerConfig<Bindings>) {
  const lines: string[] = [
    "// Auto-generated by better-wrangler - DO NOT EDIT",
  ];

  const userEntryRelative = relative(OUTPUT_DIR, worker.entryPoint).replace(
    /\.ts$/,
    "",
  );
  lines.push(`export * from '${userEntryRelative}';`);
  // export * doesn't include default exports
  lines.push(`export { default } from '${userEntryRelative}';`);

  if (worker.bindings) {
    for (const [_, binding] of Object.entries(worker.bindings)) {
      if (binding._type === "DurableObject") {
        const doBind = binding as DurableObjectBinding<any>;
        if (doBind._owner === worker.name && doBind.classPath) {
          const classPathRelative = relative(
            OUTPUT_DIR,
            doBind.classPath,
          ).replace(/\.ts$/, "");
          lines.push(
            `export { ${doBind.className} } from '${classPathRelative}';`,
          );
        }
      }
    }
  }

  const entryPath = `${OUTPUT_DIR}/${worker.name}.entry.ts`;
  writeFileSync(entryPath, lines.join("\n") + "\n");
  console.log(`Generated ${entryPath}`);

  return entryPath;
}

export function generateWranglerConfigFile(
  worker: WorkerConfig<Bindings>,
  configPaths: Map<string, string>,
) {
  const wranglerConfig = generateWranglerConfig(worker, {
    observability: { enabled: true },
    port: worker.port,
  });

  // Path is relative to the config file location (.better-wrangler/)
  wranglerConfig.main = `./${worker.name}.entry.ts`;

  const configOutputPath = `${OUTPUT_DIR}/${worker.name}.wrangler.jsonc`;
  writeFileSync(configOutputPath, JSON.stringify(wranglerConfig, null, "\t"));
  configPaths.set(worker.name, configOutputPath);

  console.log(`Generated ${configOutputPath}`);
}
