import { writeFileSync } from "fs";
import { relative, resolve } from "path";
import type { WorkerConfig, Bindings } from "../types";
import type { DurableObjectBinding } from "../../bindings/durable-object";
import { generateWranglerConfig } from "../../generate";
import { createLogger } from "../../logger";

const OUTPUT_DIR = ".better-wrangler";
const log = createLogger("sync");

/**
 * Validates that a path doesn't escape the project directory and doesn't contain
 * characters that could break import statements.
 */
function validatePath(path: string, fieldName: string) {
  const projectRoot = process.cwd();
  const resolved = resolve(projectRoot, path);

  if (!resolved.startsWith(projectRoot)) {
    throw new Error(
      `${fieldName} must be within project directory: ${path}`,
    );
  }

  // Check for characters that could break import statements
  if (path.includes("'") || path.includes('"') || path.includes("`")) {
    throw new Error(
      `${fieldName} contains invalid characters (quotes not allowed): ${path}`,
    );
  }
}

/**
 * Validates that a class name is a valid JavaScript identifier.
 */
function validateClassName(name: string) {
  if (!/^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(name)) {
    throw new Error(
      `Invalid class name "${name}". Must be a valid JavaScript identifier.`,
    );
  }
}

/**
 * Validates that a worker name contains only safe characters for file paths.
 */
function validateWorkerName(name: string) {
  if (!/^[a-zA-Z0-9._-]+$/.test(name)) {
    throw new Error(
      `Invalid worker name "${name}". Only alphanumeric characters, hyphens, underscores, and dots are allowed.`,
    );
  }
}

/**
 * Normalizes path separators to forward slashes for ESM imports (Windows compatibility).
 */
function normalizePath(path: string) {
  return path.replace(/\\/g, "/");
}

/**
 * Generates a wrapper entrypoint file that re-exports the user's worker
 * and any Durable Object classes owned by this worker.
 * This allows wrangler to find DO classes without modifying user code.
 */
export function generateEntrypoint(worker: WorkerConfig<Bindings>) {
  // Validate worker name before using it in file paths
  validateWorkerName(worker.name);
  validatePath(worker.entryPoint, "entryPoint");

  const lines: string[] = [
    "// Auto-generated by better-wrangler - DO NOT EDIT",
  ];

  const userEntryRelative = normalizePath(
    relative(OUTPUT_DIR, worker.entryPoint).replace(/\.ts$/, ""),
  );
  lines.push(`export * from '${userEntryRelative}';`);
  // export * doesn't include default exports
  lines.push(`export { default } from '${userEntryRelative}';`);

  if (worker.bindings) {
    for (const [_, binding] of Object.entries(worker.bindings)) {
      if (binding._type === "DurableObject") {
        const doBind = binding as DurableObjectBinding;
        if (doBind._owner === worker.name && doBind.classPath) {
          // Validate class path and name before using in generated code
          validatePath(doBind.classPath, "classPath");
          validateClassName(doBind.className);

          const classPathRelative = normalizePath(
            relative(OUTPUT_DIR, doBind.classPath).replace(/\.ts$/, ""),
          );
          lines.push(
            `export { ${doBind.className} } from '${classPathRelative}';`,
          );
        }
      }
    }
  }

  const entryPath = `${OUTPUT_DIR}/${worker.name}.entry.ts`;
  writeFileSync(entryPath, lines.join("\n") + "\n");
  log.debug(`Generated ${entryPath}`);

  return entryPath;
}

export function generateWranglerConfigFile(
  worker: WorkerConfig<Bindings>,
  configPaths: Map<string, string>,
) {
  const wranglerConfig = generateWranglerConfig(worker, {
    observability: { enabled: true },
    port: worker.port,
  });

  // Path is relative to the config file location (.better-wrangler/)
  wranglerConfig.main = `./${worker.name}.entry.ts`;

  const configOutputPath = `${OUTPUT_DIR}/${worker.name}.wrangler.jsonc`;
  writeFileSync(configOutputPath, JSON.stringify(wranglerConfig, null, "\t"));
  configPaths.set(worker.name, configOutputPath);

  log.debug(`Generated ${configOutputPath}`);
}
