import { describe, it, expect, beforeEach } from "vitest";
import * as path from "node:path";
import {
	createTempProject,
	readTempFile,
	tempFileExists,
} from "../utils/temp-project";
import { runCLI } from "../utils/run-cli";

describe("bw sync command", () => {
	describe("single worker", () => {
		it("creates .better-wrangler directory", async () => {
			const tempDir = await createTempProject({
				config: `
import { Worker } from "${path.resolve("./src")}";

export const testWorker = Worker({
	name: "test-worker",
	entryPoint: "./src/test-worker/index.ts",
	port: 8787,
});
`,
				workers: {
					"test-worker": `
export default {
	async fetch(request: Request): Promise<Response> {
		return new Response("Hello World");
	}
};
`,
				},
			});

			const result = await runCLI(["sync"], { cwd: tempDir });

			expect(result.exitCode).toBe(0);
			expect(await tempFileExists(tempDir, ".better-wrangler")).toBe(true);
		});

		it("generates entrypoint file for worker", async () => {
			const tempDir = await createTempProject({
				config: `
import { Worker } from "${path.resolve("./src")}";

export const testWorker = Worker({
	name: "test-worker",
	entryPoint: "./src/test-worker/index.ts",
	port: 8787,
});
`,
				workers: {
					"test-worker": `
export default {
	async fetch(request: Request): Promise<Response> {
		return new Response("Hello World");
	}
};
`,
				},
			});

			await runCLI(["sync"], { cwd: tempDir });

			const entryExists = await tempFileExists(
				tempDir,
				".better-wrangler/test-worker.entry.ts"
			);
			expect(entryExists).toBe(true);

			const entryContent = await readTempFile(
				tempDir,
				".better-wrangler/test-worker.entry.ts"
			);
			expect(entryContent).toContain("// Auto-generated by better-wrangler");
			expect(entryContent).toContain("export * from '../src/test-worker/index'");
			expect(entryContent).toContain("export { default } from '../src/test-worker/index'");
		});

		it("generates wrangler config file for worker", async () => {
			const tempDir = await createTempProject({
				config: `
import { Worker } from "${path.resolve("./src")}";

export const testWorker = Worker({
	name: "test-worker",
	entryPoint: "./src/test-worker/index.ts",
	port: 8787,
});
`,
				workers: {
					"test-worker": `
export default {
	async fetch(request: Request): Promise<Response> {
		return new Response("Hello World");
	}
};
`,
				},
			});

			await runCLI(["sync"], { cwd: tempDir });

			const configExists = await tempFileExists(
				tempDir,
				".better-wrangler/test-worker.wrangler.jsonc"
			);
			expect(configExists).toBe(true);

			const configContent = await readTempFile(
				tempDir,
				".better-wrangler/test-worker.wrangler.jsonc"
			);
			const config = JSON.parse(configContent);

			expect(config.name).toBe("test-worker");
			// main is relative to the config file location (.better-wrangler/)
			expect(config.main).toBe("./test-worker.entry.ts");
		});
	});

	describe("multiple workers", () => {
		it("generates files for all workers", async () => {
			const tempDir = await createTempProject({
				config: `
import { Worker } from "${path.resolve("./src")}";

export const worker1 = Worker({
	name: "worker-1",
	entryPoint: "./src/worker-1/index.ts",
	port: 8787,
});

export const worker2 = Worker({
	name: "worker-2",
	entryPoint: "./src/worker-2/index.ts",
	port: 8788,
});
`,
				workers: {
					"worker-1": `export default { fetch: () => new Response("Worker 1") };`,
					"worker-2": `export default { fetch: () => new Response("Worker 2") };`,
				},
			});

			await runCLI(["sync"], { cwd: tempDir });

			expect(
				await tempFileExists(tempDir, ".better-wrangler/worker-1.entry.ts")
			).toBe(true);
			expect(
				await tempFileExists(tempDir, ".better-wrangler/worker-2.entry.ts")
			).toBe(true);
			expect(
				await tempFileExists(tempDir, ".better-wrangler/worker-1.wrangler.jsonc")
			).toBe(true);
			expect(
				await tempFileExists(tempDir, ".better-wrangler/worker-2.wrangler.jsonc")
			).toBe(true);
		});
	});

	describe("workers with DurableObjects", () => {
		it("exports DO classes in entrypoint", async () => {
			const tempDir = await createTempProject({
				config: `
import { Worker, DurableObject } from "${path.resolve("./src")}";

export const testWorker = Worker({
	name: "test-worker",
	entryPoint: "./src/test-worker/index.ts",
	port: 8787,
	bindings: {
		MY_DO: DurableObject({
			name: "MY_DO",
			className: "MyDurableObject",
			classPath: "./src/shared/my-do.ts",
		}),
	},
});
`,
				workers: {
					"test-worker": `export default { fetch: () => new Response("Hello") };`,
				},
			});

			// Create the DO file
			const fs = await import("node:fs/promises");
			await fs.mkdir(path.join(tempDir, "src/shared"), { recursive: true });
			await fs.writeFile(
				path.join(tempDir, "src/shared/my-do.ts"),
				`
import { DurableObject } from "cloudflare:workers";
export class MyDurableObject extends DurableObject {
	fetch() { return new Response("DO"); }
}
`
			);

			await runCLI(["sync"], { cwd: tempDir });

			const entryContent = await readTempFile(
				tempDir,
				".better-wrangler/test-worker.entry.ts"
			);
			expect(entryContent).toContain(
				"export { MyDurableObject } from '../src/shared/my-do'"
			);
		});

		it("generates migrations in wrangler config", async () => {
			const tempDir = await createTempProject({
				config: `
import { Worker, DurableObject } from "${path.resolve("./src")}";

export const testWorker = Worker({
	name: "test-worker",
	entryPoint: "./src/test-worker/index.ts",
	port: 8787,
	bindings: {
		MY_DO: DurableObject({
			name: "MY_DO",
			className: "MyDurableObject",
			classPath: "./src/shared/my-do.ts",
		}),
	},
});
`,
				workers: {
					"test-worker": `export default { fetch: () => new Response("Hello") };`,
				},
			});

			const fs = await import("node:fs/promises");
			await fs.mkdir(path.join(tempDir, "src/shared"), { recursive: true });
			await fs.writeFile(
				path.join(tempDir, "src/shared/my-do.ts"),
				`export class MyDurableObject {}`
			);

			await runCLI(["sync"], { cwd: tempDir });

			const configContent = await readTempFile(
				tempDir,
				".better-wrangler/test-worker.wrangler.jsonc"
			);
			const config = JSON.parse(configContent);

			expect(config.durable_objects).toEqual({
				bindings: [{ name: "MY_DO", class_name: "MyDurableObject" }],
			});
			expect(config.migrations).toEqual([
				{ tag: "v1", new_classes: ["MyDurableObject"] },
			]);
		});
	});

	describe("workers with D1", () => {
		it("generates d1_databases in wrangler config", async () => {
			const tempDir = await createTempProject({
				config: `
import { Worker, D1 } from "${path.resolve("./src")}";

export const testWorker = Worker({
	name: "test-worker",
	entryPoint: "./src/test-worker/index.ts",
	port: 8787,
	bindings: {
		DB: D1({ name: "my-database" }),
	},
});
`,
				workers: {
					"test-worker": `export default { fetch: () => new Response("Hello") };`,
				},
			});

			await runCLI(["sync"], { cwd: tempDir });

			const configContent = await readTempFile(
				tempDir,
				".better-wrangler/test-worker.wrangler.jsonc"
			);
			const config = JSON.parse(configContent);

			expect(config.d1_databases).toEqual([
				{ binding: "DB", database_name: "my-database" },
			]);
		});
	});

	describe("error handling", () => {
		it("fails when no config file is found", async () => {
			const tempDir = await createTempProject({});

			const result = await runCLI(["sync"], { cwd: tempDir });

			expect(result.exitCode).not.toBe(0);
		});

		it("fails when workers have no ports configured", async () => {
			const tempDir = await createTempProject({
				config: `
import { Worker } from "${path.resolve("./src")}";

export const testWorker = Worker({
	name: "test-worker",
	entryPoint: "./src/test-worker/index.ts",
});
`,
				workers: {
					"test-worker": `export default { fetch: () => new Response("Hello") };`,
				},
			});

			const result = await runCLI(["sync"], { cwd: tempDir });

			expect(result.exitCode).not.toBe(0);
			expect(result.stderr).toContain("port");
		});

		it("fails when workers have duplicate ports", async () => {
			const tempDir = await createTempProject({
				config: `
import { Worker } from "${path.resolve("./src")}";

export const worker1 = Worker({
	name: "worker-1",
	entryPoint: "./src/worker-1/index.ts",
	port: 8787,
});

export const worker2 = Worker({
	name: "worker-2",
	entryPoint: "./src/worker-2/index.ts",
	port: 8787,
});
`,
				workers: {
					"worker-1": `export default { fetch: () => new Response("1") };`,
					"worker-2": `export default { fetch: () => new Response("2") };`,
				},
			});

			const result = await runCLI(["sync"], { cwd: tempDir });

			expect(result.exitCode).not.toBe(0);
			expect(result.stderr).toContain("8787");
		});
	});
});
